"""Initial migration

Revision ID: e8fcd853e0dd
Revises: 
Create Date: 2026-05-02 18:26:12.637620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fcd853e0dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'candidates', 'elections', ['election_id'], ['id'])
    op.drop_constraint(op.f('votes_election_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'elections', ['election_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_election_id_fkey'), 'votes', 'elections', ['election_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    # ### end Alembic commands ###
